Algoritmo "dardo"

Var

       a,b,c:real

Inicio

      escreval("Digite as tres distancias: ")
      leia(a)
      leia(b)
      leia(c)
      
      se (a>b) e (a>c)então
        escreva( "MAIOR DISTANCIA = ", a)
        senão
         se ( b>c) então
          escreva( "MAIR DISTANCIA = ",b)
           senão
             escreva( "MAIR DISTANCIA = ",c)
            fimse
            fimse
Fimalgoritmo