Algoritmo "terreno"

Var
         largura, comprimento, valor, preco, area: real



Inicio

      escreva("Digite a largura do terreno: ")
      leia( largura)
      escreva("Digite o comprimento do terreno: ")
      leia(comprimento)
      escreva("Digite o valor do metro quadrado: ")
      leia(valor)

      area<-largura*comprimento
      escreval("Area do terreno = ", area)

      preco<- area*valor
      escreval("Preco do terreno = ", preco)




Fimalgoritmo